export const guatemala = [
  {
    title: "Alta Verapaz",
    mun: [
      "Chahal",
      "Chisec",
      "Cobán",
      "Fray Bartolomé de las Casas",
      "Lanquín",
      "Panzós",
      "Raxruha",
      "San Cristóbal Verapaz",
      "San Juan Chamelco",
      "San Pedro Carchá",
      "Santa Cruz Verapaz",
      "Senahú",
      "Tactic",
      "Tamahú",
      "Tucurú",
      "Santa María Cahabón",
      "Santa Catarina La Tinta",
    ],
  },
  {
    title: "Baja Verapaz",
    mun: [
      "Cubulco",
      "Granados",
      "Purulhá",
      "Rabinal",
      "Salamá",
      "San Jerónimo",
      "San Miguel Chicaj",
      "Santa Cruz El Chol",
    ],
  },
  {
    title: "Chimaltenango",
    mun: [
      "Acatenango",
      "Chimaltenango",
      "El Tejar",
      "Parramos",
      "Patzicía",
      "Patzún",
      "Pochuta",
      "San Andrés Itzapa",
      "San José Poaquil",
      "San Juan Comalapa",
      "San Martín Jilotepeque",
      "Santa Apolonia",
      "Santa Cruz Balanyá",
      "Tecpán Guatemala",
      "Yepocapa",
      "Zaragoza",
    ],
  },
  {
    title: "Chiquimula",
    mun: [
      "Camotán",
      "Chiquimula",
      "Concepción Las Minas",
      "Esquipulas",
      "Ipala",
      "Jocotán",
      "Olopa",
      "Quezaltepeque",
      "San Jacinto",
      "San José La Arada",
      "San Juan Ermita",
    ],
  },
  {
    title: "El Progreso",
    mun: [
      "El Jícaro",
      "Guastatoya",
      "Morazán",
      "San Agustín Acasaguastlán",
      "San Antonio La Paz",
      "San Cristóbal Acasaguastlán",
      "Sanarate",
    ],
  },
  {
    title: "Escuintla",
    mun: [
      "Escuintla",
      "Guanagazapa",
      "Iztapa",
      "La Democracia",
      "La Gomera",
      "Masagua",
      "Nueva Concepción",
      "Palín",
      "San José",
      "San Vicente Pacaya",
      "Santa Lucía Cotzumalguapa",
      "Siquinalá",
      "Tiquisate",
    ],
  },
  {
    title: "Guatemala",
    mun: [
      "Amatitlán",
      "Chinautla",
      "Chuarrancho",
      "Fraijanes",
      "Guatemala City",
      "Mixco",
      "Palencia",
      "Petapa",
      "San José del Golfo",
      "San José Pinula",
      "San Juan Sacatepéquez",
      "San Pedro Ayampuc",
      "San Pedro Sacatepéquez",
      "San Raymundo",
      "Santa Catarina Pinula",
      "Villa Canales",
    ],
  },
  {
    title: "Huehuetenango",
    mun: [
      "Aguacatán",
      "Chiantla",
      "Colotenango",
      "Concepción Huista",
      "Cuilco",
      "Huehuetenango",
      "Ixtahuacán",
      "Jacaltenango",
      "La Democracia",
      "La Libertad",
      "Malacatancito",
      "Nentón",
      "San Antonio Huista",
      "San Gaspar Ixchil",
      "San Juan Atitán",
      "San Juan Ixcoy",
      "San Mateo Ixtatán",
      "San Miguel Acatán",
      "San Pedro Necta",
      "San Rafael La Independencia",
      "San Rafael Petzal",
      "San Sebastián Coatán",
      "San Sebastián Huehuetenango",
      "Santa Ana Huista",
      "Santa Bárbara",
      "Santa Cruz Barillas",
      "Santa Eulalia",
      "Santiago Chimaltenango",
      "Soloma",
      "Tectitán",
      "Todos Santos Cuchumatan",
    ],
  },
  {
    title: "Izabal",
    mun: ["El Estor", "Livingston", "Los Amates", "Morales", "Puerto Barrios"],
  },
  {
    title: "Jalapa",
    mun: [
      "Jalapa",
      "Mataquescuintla",
      "Monjas",
      "San Carlos Alzatate",
      "San Luis Jilotepeque",
      "San Manuel Chaparrón",
      "San Pedro Pinula",
    ],
  },
  {
    title: "Jutiapa",
    mun: [
      "Agua Blanca",
      "Asunción Mita",
      "Atescatempa",
      "Comapa",
      "Conguaco",
      "El Adelanto",
      "El Progreso",
      "Jalpatagua",
      "Jerez",
      "Jutiapa",
      "Moyuta",
      "Pasaco",
      "Quezada",
      "San José Acatempa",
      "Santa Catarina Mita",
      "Yupiltepeque",
      "Zapotitlán",
    ],
  },
  {
    title: "Petén",
    mun: [
      "Dolores",
      "Flores",
      "La Libertad",
      "Melchor de Mencos",
      "Poptún",
      "San Andrés",
      "San Benito",
      "San Francisco",
      "San José",
      "San Luis",
      "Santa Ana",
      "Sayaxché",
      "Las Cruces",
    ],
  },
  {
    title: "Quetzaltenango",
    mun: [
      "Almolonga",
      "Cabricán",
      "Cajolá",
      "Cantel",
      "Coatepeque",
      "Colomba",
      "Concepción Chiquirichapa",
      "El Palmar",
      "Flores Costa Cuca",
      "Génova",
      "Huitán",
      "La Esperanza",
      "Olintepeque",
      "Ostuncalco",
      "Palestina de Los Altos",
      "Quetzaltenango",
      "Salcajá",
      "San Carlos Sija",
      "San Francisco La Unión",
      "San Martín Sacatepéquez",
      "San Mateo",
      "San Miguel Sigüilá",
      "Sibilia",
      "Zunil",
    ],
  },
  {
    title: "Quiché",
    mun: [
      "Canillá",
      "Chajul",
      "Chicamán",
      "Chiché",
      "Chichicastenango",
      "Chinique",
      "Cunén",
      "Ixcán",
      "Joyabaj",
      "Nebaj",
      "Pachalum",
      "Patzité",
      "Sacapulas",
      "San Andrés Sajcabajá",
      "San Antonio Ilotenango",
      "San Bartolomé Jocotenango",
      "San Juan Cotzal",
      "San Pedro Jocopilas",
      "Santa Cruz del Quiché",
      "Uspantán",
      "Zacualpa",
    ],
  },
  {
    title: "Retalhuleu",
    mun: [
      "Champerico",
      "El Asintal",
      "Nuevo San Carlos",
      "Retalhuleu",
      "San Andrés Villa Seca",
      "San Felipe",
      "San Martín Zapotitlán",
      "San Sebastián",
      "Santa Cruz Muluá",
    ],
  },
  {
    title: "Sacatepéquez",
    mun: [
      "Alotenango",
      "Antigua",
      "Ciudad Vieja",
      "Jocotenango",
      "Magdalena Milpas Altas",
      "Pastores",
      "San Antonio Aguas Calientes",
      "San Bartolomé Milpas Altas",
      "San Lucas Sacatepéquez",
      "San Miguel Dueñas",
      "Santa Catarina Barahona",
      "Santa Lucía Milpas Altas",
      "Santa María de Jesús",
      "Santiago Sacatepéquez",
      "Santo Domingo Xenacoj",
      "Sumpango",
    ],
  },
  {
    title: "San Marcos",
    mun: [
      "Ayutla",
      "Catarina",
      "Comitancillo",
      "Concepción Tutuapa",
      "El Quetzal",
      "El Rodeo",
      "El Tumbador",
      "Esquipulas Palo Gordo",
      "Ixchiguan",
      "La Reforma",
      "Malacatán",
      "Nuevo Progreso",
      "Ocós",
      "Pajapita",
      "San Antonio Sacatepéquez",
      "San Cristóbal Cucho",
      "San José Ojetenam",
      "San Lorenzo",
      "San Marcos",
      "San Miguel Ixtahuacán",
      "San Pablo",
      "San Pedro Sacatepéquez",
      "Sibinal",
      "Sipacapa",
      "Tacaná",
      "Tajumulco",
      "Tejutla",
    ],
  },
];
